title: Plastic Images Classifier
description: Classify plastic images using deep learning
about:
  This is a Plastic Images Classifier using Deep Learning built on top of Pytorch.

code: 

sampleImages:
  - name: plastic water bottle
    url: https://5.imimg.com/data5/SD/JK/MY-10914613/plastic-water-bottle-500x500.jpg
  - name: shampoo bottles
    url: https://www.calgary.ca/UEP/WRS/PublishingImages/What-goes-where/items/Shampoo-bottle-160px.jpg
  - name: tupperwares
    url: https://images-na.ssl-images-amazon.com/images/I/61cp079PULL._SL1500_.jpg
  


