title: Plastic Images Classifier
description: Classify plastic images using deep learning
about:
  This is a Plastic Images Classifier using Deep Learning built on top of Pytorch.

code: https://github.com/cnll0075/knowYourPlastic/

sampleImages:
  - name: plastic water bottle
    url: https://5.imimg.com/data5/SD/JK/MY-10914613/plastic-water-bottle-500x500.jpg
  - name: motor oil bottles
    url: https://static.turbosquid.com/Preview/2014/07/07__05_28_49/motor_oil_bottles.jpgf4954ae6-35a7-4120-8abb-38240aaf6193Original.jpg
  - name: tupperwares
    url: https://images-na.ssl-images-amazon.com/images/I/61cp079PULL._SL1500_.jpg
  


